### ISSUE TITLE
Create Resume

### ISSUE THREAD

**Issue by Puja-Saraf** [Puja-Saraf/CoDev-hh2#13]
Create your profile on the website. (Invalid Github ids won't be accepted). Go to your profile page and click on the "View Resume" button at the bottom, you will get your own resume and can share the link!

You need to submit the resume link and screenshots.  There's a folder named **Resumes** in **contributing** branch, inside that folder, you need to create a folder named as your GitHub id, and submit the resume link in a txt file and the screenshots inside the folder.
You can refer to the example folder(named as Puja-Saraf) in the Resumes folder.

This issue is open to all.

**Comment by satyamrs00** [comment]
there is no resumes folder @Puja-Saraf

**Comment by Puja-Saraf** [comment]
> there is no resumes folder @Puja-Saraf should i create one ?

Resumes folder is in contributing branch

**Comment by aishwarya1735** [comment]
Hey can this issue be assigned to me?

**Comment by Puja-Saraf** [comment]
> Hey can this issue be assigned to me?

The issue is open for all. Go ahead!

**Comment by aishwarya1735** [comment]
Okayy
